### ISSUE TITLE
Windows version, please

### ISSUE THREAD

**Issue by apometron** [e-shulitsky/simpleblogger#2]
Hello !!! =DDD

I need a Windows version of SimpleBlogger, because I dont have Linux.

Thank You !!! =DDD

Regards,
Rodrigo Cesar Banhara

**Comment by apometron** [comment]
I have Windows 8.1.

**Comment by jsnjack** [comment]
Hello @apometron 
There is no Windows version. And I have some doubts if it can be successfully ported. But you can try by cloning repository installing gtk from here http://www.gtk.org/download/windows.php and all dependencies from https://github.com/jsnjack/simpleblogger/blob/master/simpleblogger.spec. If you manage to start GUI, I will change linux specific paths to Windows-friendly (if it is needed)
